#!/usr/bin/env bash
set -e

case "$1" in
    "build")
        make -j`nproc`
        ;;
    "buildconf")
        ./buildconf
        ;;
    "configure")
        ./configure
        ;;
    "test")
        TESTS="$2" make test
        ;;
    *)
        echo "Unknown command"
        exit 2
        ;;
esac
