#!/usr/bin/env bash
set -e

function doConfigure()
{
    if [ ! -f configure ]; then
        ./buildconf
    fi
    ./configure
}

function doBuild()
{
	if [ ! -f Makefile ]; then
		doConfigure
	fi;
	make -j`nproc`
}

function doTest()
{
	if [ ! -f Makefile ]; then
        doConfigure
    fi;
    TESTS="$1" make -j`nproc` test
}

case "$1" in
    "build")
        doBuild
        ;;
    "configure")
        doConfigure
        ;;
    "test")
        doTest "$1"
        ;;
    *)
        echo "Unknown command"
        exit 2
        ;;
esac
